Vagrant.configure("2") do |config|
  SERVERS=1
  ##################
  # Middleware     #
  ##################
  config.vm.define "middleware" do |v|
    v.vm.box = "centos-64-x64-vbox4210"
    v.vm.provider "virtualbox" do |vbox|
      vbox.memory = 400
    end
    v.vm.network "private_network", ip: "192.168.231.10"
    v.vm.provision :puppet, :options => ["--pluginsync"], :module_path => ["deploy/modules", "deploy/external-modules"] do |puppet|
      puppet.manifests_path = "deploy"
      puppet.manifest_file = "site.pp"
    end
    v.vm.hostname = "middleware"
    v.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  end
  ######################
  # mcollective servers#
  ######################
  config.vm.define "mcserver" do |v|
    v.vm.box = "centos-64-x64-vbox4210"
    v.vm.provider "virtualbox" do |vbox|
      vbox.memory = 300
    end
    v.vm.network "private_network", ip: "192.168.231.11"
    v.vm.provision :puppet, :options => ["--pluginsync"], :module_path => ["deploy/modules", "deploy/external-modules"] do |puppet|
      puppet.manifests_path = "deploy"
      puppet.manifest_file = "site.pp"
    end
    v.vm.hostname = "mcserver"
    v.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  end
  ######################
  # mcollective client #
  # the machine with:  #
  #     MCOMASTER      #
  ######################
  config.vm.define "mcomaster" do |v|
    v.vm.box = "centos-64-x64-vbox4210"
    v.vm.provider "virtualbox" do |vbox|
      vbox.memory = 600
    end
    v.vm.network "forwarded_port", guest: 8080, host: 8080
    v.vm.network "private_network", ip: "192.168.231.20"
    v.vm.provision :puppet, :options => ["--pluginsync"], :module_path => ["deploy/modules", "deploy/external-modules"] do |puppet|
      puppet.manifests_path = "deploy"
      puppet.manifest_file = "site.pp"
    end
    v.vm.hostname = "mcomaster"
    v.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  end
end
